name: example
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_icons:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  # split_icon: ^0.2.0  

flutter_icons:
  includes:
    - ant

flutter:


  uses-material-design: true
