library flutter_icons;

export 'src/ionicons.dart';
export 'src/ant_design.dart';
export 'src/font_awesome.dart';
export 'src/material_icons.dart';
export 'src/entypo.dart';
export 'src/evil_icons.dart';
export 'src/feather.dart';
export 'src/material_community_icons.dart';
export 'src/octicons.dart';
export 'src/simple_line_icons.dart';
export 'src/zocial.dart';
export 'src/foundation.dart';
export 'src/font_awesome_5.dart';
export 'src/font_awesome_5_solid.dart';
export 'src/font_awesome_5_brands.dart';
export 'src/icon_toggle.dart';
export 'src/weather_icons.dart';
